// Generated by @lynx-js/autolink-codegen. Edit the method bodies as needed.
#include "napi.h"

#ifdef USE_WEAK_SUFFIX_NAPI
#include "weak_napi_defines.h"
#endif

#ifdef LYNX_LIBRARY_USE_PRIMJS_NAPI_MODULE
#undef NAPI_MODULE
#ifdef LYNX_LIBRARY_MANUAL_NAPI_REGISTRATION
#define LYNX_LIBRARY_NAPI_REGISTRATION_ATTRIBUTE
#else
#define LYNX_LIBRARY_NAPI_REGISTRATION_ATTRIBUTE __attribute__((constructor))
#endif
#define NAPI_MODULE(modname, regfunc)                                      \
  EXTERN_C_START                                                           \
  static napi_module _module_##modname = {                                 \
      NAPI_MODULE_VERSION, 0, __FILE__, regfunc, #modname, nullptr,        \
      {nullptr, nullptr, nullptr, nullptr}};                                \
  void _napi_register_xx_##modname(void)                                   \
      LYNX_LIBRARY_NAPI_REGISTRATION_ATTRIBUTE;                             \
  void _napi_register_xx_##modname(void) {                                 \
    napi_module_register(&_module_##modname);                              \
  }                                                                        \
  EXTERN_C_END
#endif

namespace {

void Check(napi_env env, napi_status status) {
  if (status != napi_ok) {
    napi_throw_error(env, nullptr, "N-API call failed");
  }
}

void SetFunction(
    napi_env env,
    napi_value object,
    const char* name,
    napi_callback callback) {
  napi_value function;
  Check(env, napi_create_function(
      env, name, NAPI_AUTO_LENGTH, callback, nullptr, &function));
  Check(env, napi_set_named_property(env, object, name, function));
}

Napi::Value SetValue(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  // Method:
  //   setValue(
  //     key: string,
  //     value: string,
  //   ): void
  // types/napi-native-module.d.ts:3
  if (info.Length() < 2) {
    return env.Undefined();
  }
  // Param: key: string
  // types/napi-native-module.d.ts:3
  Napi::String key = info[0].As<Napi::String>();
  (void)key;
  // Param: value: string
  // types/napi-native-module.d.ts:3
  Napi::String value = info[1].As<Napi::String>();
  (void)value;
  return env.Undefined();
}

Napi::Value GetValue(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  // Method:
  //   getValue(
  //     key: string,
  //   ): string | null
  // types/napi-native-module.d.ts:4
  if (info.Length() < 1) {
    return env.Undefined();
  }
  // Param: key: string
  // types/napi-native-module.d.ts:4
  Napi::String key = info[0].As<Napi::String>();
  (void)key;
  return env.Null();
}

Napi::Value Clear(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  // Method:
  //   clear(): void
  // types/napi-native-module.d.ts:5
  return env.Undefined();
}

napi_value SetValueCallback(napi_env env, napi_callback_info info) {
  return SetValue(Napi::CallbackInfo(env, info));
}

napi_value GetValueCallback(napi_env env, napi_callback_info info) {
  return GetValue(Napi::CallbackInfo(env, info));
}

napi_value ClearCallback(napi_env env, napi_callback_info info) {
  return Clear(Napi::CallbackInfo(env, info));
}

void BindLynxFastImageModuleNapi(napi_env env, napi_value exports) {
  SetFunction(env, exports, "setValue", SetValueCallback);
  SetFunction(env, exports, "getValue", GetValueCallback);
  SetFunction(env, exports, "clear", ClearCallback);
}

static napi_value CreateLynxFastImageModuleNapi(napi_env env, napi_value exports) {
  BindLynxFastImageModuleNapi(env, exports);
  return exports;
}

}  // namespace

extern "C" napi_value LynxAutolinkCreateLynxFastImageModuleNapi(
    napi_env env,
    napi_value exports,
    const char* module_name,
    void* opaque) {
  (void)module_name;
  (void)opaque;
  return CreateLynxFastImageModuleNapi(env, exports);
}

#ifdef LYNX_LIBRARY_USE_PRIMJS_NAPI_MODULE
NAPI_MODULE(LynxFastImageModuleNapi, CreateLynxFastImageModuleNapi)
#endif

#ifdef USE_WEAK_SUFFIX_NAPI
#include "weak_napi_undefs.h"
#endif
